"""Release workflow models -- represents the full .github/workflows/release.yml."""

from __future__ import annotations

from typing import Annotated, Any

from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    Field,
    model_serializer,
    model_validator,
)


class WorkflowInput(BaseModel):
    """A single input for workflow_dispatch."""

    description: str = ""
    type: str = "string"
    required: bool = False


class WorkflowDispatch(BaseModel):
    """The workflow_dispatch trigger."""

    inputs: dict[str, WorkflowInput] = Field(
        default_factory=lambda: {
            "plan": WorkflowInput(
                description="Release plan JSON (generated by uvr release).",
                type="string",
                required=True,
            ),
        }
    )


class WorkflowTrigger(BaseModel):
    """The ``on:`` block. Editable -- users can add triggers."""

    model_config = ConfigDict(extra="allow")

    workflow_dispatch: WorkflowDispatch = Field(default_factory=WorkflowDispatch)


class Job(BaseModel):
    """Base for all jobs. Common overridable fields."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    runs_on: str = Field(default="ubuntu-latest", alias="runs-on")
    if_condition: str | None = Field(default=None, alias="if")
    needs: list[str] = Field(default_factory=list)
    environment: str | None = None
    concurrency: str | dict | None = None
    timeout_minutes: int | None = Field(default=None, alias="timeout-minutes")
    env: dict[str, str] | None = None
    strategy: dict = Field(default_factory=dict)
    steps: list[dict] = Field(default_factory=list)

    @model_serializer(mode="wrap")
    def _drop_empty(self, handler: Any) -> dict:
        d = handler(self)
        if "needs" in d and d["needs"] == []:
            del d["needs"]
        if "strategy" in d and d["strategy"] == {}:
            del d["strategy"]
        return d


# Shorthand for GitHub Actions expressions referencing the release plan.
_PLAN = "fromJSON(inputs.plan)"


def _gha(expr: str) -> str:
    """Wrap *expr* in GitHub Actions ``${{ }}`` interpolation."""
    return "${{ " + expr + " }}"


_CHECKOUT = {
    "id": "checkout",
    "uses": "actions/checkout@v4",
    "with": {"fetch-depth": 0},
}
_SETUP_UV = {
    "id": "setup-uv",
    "uses": "astral-sh/setup-uv@v5",
    "with": {"python-version": _gha(f"{_PLAN}.python_version")},
}


def _needs_validator(*required: str):
    """Create a model_validator that ensures needs contains the required jobs."""

    @model_validator(mode="after")
    def _check(self: Job) -> Job:
        for dep in required:
            if dep not in self.needs:
                self.needs.insert(0, dep)
        return self

    return _check


_UNSET: Any = object()


def WarnIfChanged(  # noqa: N802
    tp: Any,
    *,
    default: Any = _UNSET,
    default_factory: Any = _UNSET,
    msg: str = "",
    **field_kwargs: Any,
) -> Any:
    """Return an ``Annotated`` type that warns when a field is modified.

    Bundles the type, ``Field(default=…)`` or ``Field(default_factory=…)``
    and an ``AfterValidator`` into one annotation.
    """
    import warnings

    assert not (default is _UNSET and default_factory is _UNSET), (
        "WarnIfChanged requires default or default_factory"
    )

    if default is not _UNSET:
        expected = default
        field_kwargs["default"] = default
    else:
        expected = default_factory()
        field_kwargs["default_factory"] = default_factory

    def _check(v: Any) -> Any:
        if v != expected:
            warnings.warn(
                msg or "frozen field was modified from its default",
                UserWarning,
                stacklevel=2,
            )
        return v

    return Annotated[tp, Field(**field_kwargs), AfterValidator(_check)]


class ValidatePlanJob(Job):
    """The validate-plan job. Frozen -- runs first to validate plan JSON."""

    steps: WarnIfChanged(  # ty: ignore[invalid-type-form]
        list[dict],
        default_factory=lambda: [
            _SETUP_UV,
            {
                "id": "validate-plan",
                "name": "Validate release plan",
                "env": {"UVR_PLAN": "${{ inputs.plan }}"},
                "run": "uv run uvr validate-plan",
            },
        ],
        msg="validate-plan.steps was modified",
    )


class BuildJob(Job):
    """The build job. Frozen -- immutable fields enforced per-field."""

    if_condition: WarnIfChanged(  # ty: ignore[invalid-type-form]
        str | None,
        default=_gha(f"!contains({_PLAN}.skip, 'build')"),
        msg="build.if was modified",
        alias="if",
    )
    strategy: WarnIfChanged(  # ty: ignore[invalid-type-form]
        dict,
        default_factory=lambda: {
            "fail-fast": True,
            "matrix": {"runner": _gha(f"{_PLAN}.build_matrix")},
        },
        msg="build.strategy was modified",
    )
    runs_on: WarnIfChanged(  # ty: ignore[invalid-type-form]
        str,
        default=_gha("matrix.runner"),
        msg="build.runs-on was modified",
        alias="runs-on",
    )
    steps: WarnIfChanged(  # ty: ignore[invalid-type-form]
        list[dict],
        default_factory=lambda: [
            _CHECKOUT,
            _SETUP_UV,
            {
                "id": "build",
                "name": "Build packages",
                "env": {
                    "GH_TOKEN": "${{ github.token }}",
                    "UVR_PLAN": "${{ inputs.plan }}",
                },
                "run": "uv run uvr build --runner '${{ toJSON(matrix.runner) }}'",
            },
            {
                "id": "upload",
                "uses": "actions/upload-artifact@v4",
                "with": {
                    "name": "wheels-${{ join(matrix.runner, '-') }}",
                    "path": "dist/*.whl",
                    "if-no-files-found": "error",
                },
            },
        ],
        msg="build.steps was modified",
    )
    _ensure_needs = _needs_validator("validate_plan")


class ReleaseJob(Job):
    """The release job. Frozen -- immutable fields enforced per-field."""

    if_condition: WarnIfChanged(  # ty: ignore[invalid-type-form]
        str | None,
        default=_gha(f"always() && !failure() && !contains({_PLAN}.skip, 'release')"),
        msg="release.if was modified",
        alias="if",
    )
    strategy: WarnIfChanged(  # ty: ignore[invalid-type-form]
        dict,
        default_factory=lambda: {
            "fail-fast": False,
            "matrix": {"include": _gha(f"{_PLAN}.release_matrix")},
        },
        msg="release.strategy was modified",
    )
    steps: WarnIfChanged(  # ty: ignore[invalid-type-form]
        list[dict],
        default_factory=lambda: [
            {
                "id": "download",
                "uses": "actions/download-artifact@v4",
                "with": {
                    "pattern": "wheels-*",
                    "merge-multiple": True,
                    "path": "dist",
                    "run-id": _gha(
                        f"{_PLAN}.reuse_run_id != '' && {_PLAN}.reuse_run_id || github.run_id"
                    ),
                },
            },
            {
                "id": "publish",
                "uses": "softprops/action-gh-release@v2",
                "with": {
                    "tag_name": "${{ matrix.tag }}",
                    "name": "${{ matrix.title }}",
                    "body": "${{ matrix.body }}",
                    "files": "dist/${{ matrix.dist_name }}-${{ matrix.version }}*.whl",
                    "make_latest": "${{ matrix.make_latest }}",
                },
            },
        ],
        msg="release.steps was modified",
    )
    _ensure_needs = _needs_validator("build")


class FinalizeJob(Job):
    """The finalize job. Frozen -- immutable fields enforced per-field."""

    if_condition: WarnIfChanged(  # ty: ignore[invalid-type-form]
        str | None,
        default=_gha(f"always() && !failure() && !contains({_PLAN}.skip, 'finalize')"),
        msg="finalize.if was modified",
        alias="if",
    )
    steps: WarnIfChanged(  # ty: ignore[invalid-type-form]
        list[dict],
        default_factory=lambda: [
            _CHECKOUT,
            _SETUP_UV,
            {
                "id": "finalize",
                "name": "Finalize release",
                "env": {"UVR_PLAN": "${{ inputs.plan }}"},
                "run": "uv run uvr finalize",
            },
        ],
        msg="finalize.steps was modified",
    )
    _ensure_needs = _needs_validator("release")


class WorkflowJobs(BaseModel):
    """All jobs in the release workflow."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    validate_plan: ValidatePlanJob = Field(default_factory=ValidatePlanJob)
    build: BuildJob = Field(default_factory=BuildJob)
    release: ReleaseJob = Field(default_factory=ReleaseJob)
    finalize: FinalizeJob = Field(default_factory=FinalizeJob)


class ReleaseWorkflow(BaseModel):
    """Full representation of .github/workflows/release.yml.

    The YAML file is the source of truth. This model validates its
    structure after edits made via ``uvr workflow``. The Jinja2 template
    generates the initial YAML; this model ensures user edits don't
    break it.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    name: str = "Release Wheels"
    on: WorkflowTrigger = Field(default_factory=WorkflowTrigger)
    permissions: dict[str, str] = Field(default_factory=lambda: {"contents": "write"})
    jobs: WorkflowJobs = Field(default_factory=WorkflowJobs)

    @model_validator(mode="before")
    @classmethod
    def _normalize_on_key(cls, data: Any) -> Any:
        """PyYAML parses ``on:`` as boolean ``True`` -- normalize to string."""
        if isinstance(data, dict) and True in data:
            data["on"] = data.pop(True)
        return data


JOB_ORDER: list[str] = [
    "validate_plan",
    "build",
    "release",
    "finalize",
]
"""Canonical ordering of jobs in the release workflow pipeline."""
