"""Release workflow models -- validation schema for .github/workflows/release.yml.

The bundled YAML template (``templates/release/``) is the source of truth for
workflow content.  These models validate structure and types when a user runs
``uvr validate``.  Fields annotated with ``Frozen`` are template-controlled and
should not be user-edited; the annotation drives frozen-path diffing at
validation time.
"""

from __future__ import annotations

from typing import Annotated, Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    model_serializer,
    model_validator,
)


# ---------------------------------------------------------------------------
# Frozen marker
# ---------------------------------------------------------------------------


class _FrozenMeta:
    """Marker metadata for template-controlled fields.

    Attach via ``Annotated[T, Frozen]`` on Job subclass fields.  At validation
    time ``frozen_paths()`` introspects the model tree to collect these paths
    and compares them against the bundled template.
    """


Frozen = _FrozenMeta()
"""Singleton instance used in ``Annotated`` metadata."""


def frozen_paths(model: type[BaseModel], prefix: str = "") -> list[str]:
    """Collect dot-separated YAML paths for all ``Frozen``-annotated fields.

    Recurses into nested ``BaseModel`` fields so that
    ``frozen_paths(ReleaseWorkflow)`` returns paths like
    ``"jobs.build.steps"`` ready for comparison with ``_yaml_get()``.
    """
    paths: list[str] = []
    for name, info in model.model_fields.items():
        key = info.alias or name
        full = f"{prefix}.{key}" if prefix else key

        # Check for Frozen in Annotated metadata
        for meta in info.metadata:
            if isinstance(meta, _FrozenMeta):
                paths.append(full)
                break

        # Recurse into nested BaseModel fields
        ann = info.annotation
        if isinstance(ann, type) and issubclass(ann, BaseModel):
            paths.extend(frozen_paths(ann, full))

    return paths


# ---------------------------------------------------------------------------
# Trigger models
# ---------------------------------------------------------------------------


class WorkflowInput(BaseModel):
    """A single input for workflow_dispatch."""

    description: str = ""
    type: str = "string"
    required: bool = False


class WorkflowDispatch(BaseModel):
    """The workflow_dispatch trigger."""

    inputs: dict[str, WorkflowInput] = Field(
        default_factory=lambda: {
            "plan": WorkflowInput(
                description="Release plan JSON (generated by uvr release).",
                type="string",
                required=True,
            ),
        }
    )


class WorkflowTrigger(BaseModel):
    """The ``on:`` block. Editable -- users can add triggers."""

    model_config = ConfigDict(extra="allow")

    workflow_dispatch: WorkflowDispatch = Field(default_factory=WorkflowDispatch)


# ---------------------------------------------------------------------------
# Job models
# ---------------------------------------------------------------------------


class Job(BaseModel):
    """Base for all jobs. Common overridable fields."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    runs_on: str = Field(default="ubuntu-latest", alias="runs-on")
    if_condition: str | None = Field(default=None, alias="if")
    needs: list[str] = Field(default_factory=list)
    environment: str | None = None
    concurrency: str | dict | None = None
    timeout_minutes: int | None = Field(default=None, alias="timeout-minutes")
    env: dict[str, str] | None = None
    strategy: dict = Field(default_factory=dict)
    steps: list[dict] = Field(default_factory=list)

    @model_serializer(mode="wrap")
    def _drop_empty(self, handler: Any) -> dict:
        d = handler(self)
        if "needs" in d and d["needs"] == []:
            del d["needs"]
        if "strategy" in d and d["strategy"] == {}:
            del d["strategy"]
        return d


def _needs_validator(*required: str):
    """Create a model_validator that ensures needs contains the required jobs."""

    @model_validator(mode="after")
    def _check(self: Job) -> Job:
        for dep in required:
            if dep not in self.needs:
                self.needs.insert(0, dep)
        return self

    return _check


class ValidatePlanJob(Job):
    """The validate-plan job."""

    steps: Annotated[list[dict], Frozen] = Field(default_factory=list)


class BuildJob(Job):
    """The build job."""

    if_condition: Annotated[str | None, Frozen] = Field(default=None, alias="if")
    strategy: Annotated[dict, Frozen] = Field(default_factory=dict)
    runs_on: Annotated[str, Frozen] = Field(default="ubuntu-latest", alias="runs-on")
    steps: Annotated[list[dict], Frozen] = Field(default_factory=list)
    _ensure_needs = _needs_validator("validate_plan")


class ReleaseJob(Job):
    """The release job."""

    if_condition: Annotated[str | None, Frozen] = Field(default=None, alias="if")
    strategy: Annotated[dict, Frozen] = Field(default_factory=dict)
    steps: Annotated[list[dict], Frozen] = Field(default_factory=list)
    _ensure_needs = _needs_validator("build")


class FinalizeJob(Job):
    """The finalize job."""

    if_condition: Annotated[str | None, Frozen] = Field(default=None, alias="if")
    steps: Annotated[list[dict], Frozen] = Field(default_factory=list)
    _ensure_needs = _needs_validator("release")


# ---------------------------------------------------------------------------
# Top-level models
# ---------------------------------------------------------------------------


class WorkflowJobs(BaseModel):
    """All jobs in the release workflow."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    validate_plan: ValidatePlanJob = Field(default_factory=ValidatePlanJob)
    build: BuildJob = Field(default_factory=BuildJob)
    release: ReleaseJob = Field(default_factory=ReleaseJob)
    finalize: FinalizeJob = Field(default_factory=FinalizeJob)


class ReleaseWorkflow(BaseModel):
    """Validation schema for .github/workflows/release.yml.

    The bundled YAML template is the source of truth for content.
    This model validates structure after user edits.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    name: str = "Release Wheels"
    on: WorkflowTrigger = Field(default_factory=WorkflowTrigger)
    permissions: dict[str, str] = Field(default_factory=lambda: {"contents": "write"})
    jobs: WorkflowJobs = Field(default_factory=WorkflowJobs)

    @model_validator(mode="before")
    @classmethod
    def _normalize_on_key(cls, data: Any) -> Any:
        """PyYAML parses ``on:`` as boolean ``True`` -- normalize to string."""
        if isinstance(data, dict) and True in data:
            data["on"] = data.pop(True)
        return data


JOB_ORDER: list[str] = [
    "validate_plan",
    "build",
    "release",
    "finalize",
]
"""Canonical ordering of jobs in the release workflow pipeline."""
