"""Execution: run pre-computed commands from a ReleasePlan."""

from __future__ import annotations

import sys
from collections.abc import Sequence
from concurrent.futures import ThreadPoolExecutor, as_completed

from .hooks import ReleaseHook
from .models import (
    BuildStage,
    Command,
    ReleasePlan,
    ShellCommand,
    _validate_runner_key,
)


class ReleaseExecutor:
    """Runs pre-computed commands from a ReleasePlan.

    The executor contains NO domain logic — it just calls ``cmd.execute()``
    on the command objects generated by the planner.
    """

    def __init__(self, plan: ReleasePlan, hook: ReleaseHook | None = None) -> None:
        self.plan = plan
        self.hook = hook or ReleaseHook()

    def build(self, *, runner: str | list[str] | None = None) -> None:
        """Run build stages.

        Args:
            runner: Runner labels identifying which ``build_commands`` entry
                to execute.  Accepts a JSON string (from CI), a list, or
                ``None`` to run all entries.
        """
        if runner is not None:
            key = _validate_runner_key(runner)
            runner_list = list(key)
            stages = self.plan.build_commands.get(key, [])
        else:
            # Local mode: merge stages across runners, deduplicating packages
            # that appear in multiple runner entries.
            runner_list = []
            seen_packages: set[str] = set()
            stages = []
            for key in self.plan.build_commands:
                for stage in self.plan.build_commands[key]:
                    deduped_pkgs = {
                        pkg: cmds
                        for pkg, cmds in stage.packages.items()
                        if pkg not in seen_packages
                    }
                    # Always include setup/cleanup from first runner only
                    if deduped_pkgs or (not seen_packages and stage.setup):
                        seen_packages.update(deduped_pkgs)
                        stages.append(
                            BuildStage(
                                setup=stage.setup if not stages else [],
                                packages=deduped_pkgs,
                                cleanup=stage.cleanup if not stages else [],
                            )
                        )

        self.hook.pre_build(self.plan, runner=runner_list or None)

        for stage in stages:
            self._run_commands_or_exit(stage.setup)
            packages = sorted(stage.packages)
            self.hook.pre_build_stage(self.plan, packages, runner=runner_list or None)
            self._run_packages(stage)
            self.hook.post_build_stage(self.plan, packages, runner=runner_list or None)
            self._run_commands_or_exit(stage.cleanup)

        self.hook.post_build(self.plan, runner=runner_list or None)

    def publish(self) -> None:
        """Run publish commands."""
        self.hook.pre_release(self.plan)
        self._run_commands_or_exit(self.plan.release_commands)
        self.hook.post_release(self.plan)

    def publish_to_index(self) -> None:
        """Run index publishing commands (upload wheels to package indexes)."""
        self.hook.pre_publish(self.plan)
        self._run_commands_or_exit(self.plan.publish_commands)
        self.hook.post_publish(self.plan)

    def bump(self) -> None:
        """Run bump commands (version bumps, baseline tags, push)."""
        self.hook.pre_bump(self.plan)
        self._run_commands_or_exit(self.plan.bump_commands)
        self.hook.post_bump(self.plan)

    def run(self) -> None:
        """Execute all phases: build -> publish -> publish_to_index -> bump."""
        self.build()
        self.publish()
        self.publish_to_index()
        self.bump()

    def _run_packages(self, stage: BuildStage) -> None:
        """Run package builds, parallelising across packages."""
        if not stage.packages:
            return

        failures: list[str] = []

        def _run_pkg(pkg: str, cmds: list[ShellCommand]) -> str | None:
            self.hook.pre_build_package(self.plan, pkg)
            if not self._run_commands(cmds, prefix=pkg):
                return pkg
            self.hook.post_build_package(self.plan, pkg)
            return None

        with ThreadPoolExecutor(max_workers=len(stage.packages)) as pool:
            futures = {
                pool.submit(_run_pkg, pkg, cmds): pkg
                for pkg, cmds in stage.packages.items()
            }
            for future in as_completed(futures):
                failed = future.result()
                if failed is not None:
                    failures.append(failed)

        if failures:
            print(
                f"Stage failed for: {', '.join(sorted(failures))}",
                file=sys.stderr,
            )
            sys.exit(1)

    @staticmethod
    def _run_commands_or_exit(commands: Sequence[Command]) -> None:
        """Run commands sequentially, exiting on failure."""
        if not ReleaseExecutor._run_commands(commands):
            sys.exit(1)

    @staticmethod
    def _run_commands(commands: Sequence[Command], *, prefix: str = "") -> bool:
        """Run commands sequentially.  Return ``False`` on first failure."""
        tag = f"[{prefix}] " if prefix else ""
        for cmd in commands:
            if cmd.label:
                print(f"  {tag}{cmd.label}")
            result = cmd.execute()
            if cmd.check and result.returncode != 0:
                print(
                    f"{tag}Command failed (exit {result.returncode}): {cmd.label}",
                    file=sys.stderr,
                )
                return False
        return True
