"""Workflow state extraction and rendering helpers."""

from __future__ import annotations

from pathlib import Path

from ._common import TEMPLATES_DIR, _WorkflowConfig, _empty_hooks


def _get_workflow_state(
    path: Path,
) -> tuple[dict[str, list[dict]], _WorkflowConfig]:
    """Extract hooks and workflow config from release.yml.

    Returns:
        (hooks, config) where hooks maps phase -> step list and config
        captures permissions and per-hook job-level settings.
    """
    import yaml

    hooks = _empty_hooks()
    config = _WorkflowConfig()
    if not path.exists():
        return hooks, config

    try:
        with open(path) as f:
            doc = yaml.safe_load(f)
    except yaml.YAMLError as exc:
        raise SystemExit(
            f"error: {path} contains invalid YAML and cannot be parsed.\n"
            f"  {exc}\n\n"
            "Run `uvr init --force` to discard the existing file and regenerate."
        ) from None

    if not doc:
        return hooks, config

    # Extract top-level permissions
    raw_perms = doc.get("permissions")
    if isinstance(raw_perms, dict):
        config.permissions = {k: str(v) for k, v in raw_perms.items()}

    if "jobs" not in doc:
        return hooks, config

    jobs = doc["jobs"]
    job_to_hook = {
        "pre-build": "pre_build",
        "post-build": "post_build",
        "pre-release": "pre_release",
        "post-release": "post_release",
    }

    # Keys generated by the template that are NOT user-configurable
    _template_keys = {"steps", "needs"}

    for job_name, hook_key in job_to_hook.items():
        job = jobs.get(job_name)
        if not job or "steps" not in job:
            continue
        steps = job["steps"]
        after_export = False
        for step in steps:
            if not isinstance(step, dict):
                continue
            if step.get("name") == "Export plan context":
                after_export = True
                continue
            if after_export:
                hooks[hook_key].append(dict(step))

        # Extract all job-level settings (except template-managed keys)
        job_settings = {k: v for k, v in job.items() if k not in _template_keys}
        if job_settings:
            config.hook_jobs[hook_key] = job_settings

    return hooks, config


def _step_to_yaml(step: dict) -> str:
    """Convert a step dict to YAML for embedding in the workflow template.

    Returns the YAML mapping body (no leading ``- ``). The caller or
    Jinja2 ``indent`` filter handles indentation of continuation lines.
    """
    import yaml

    class _Dumper(yaml.SafeDumper):
        pass

    def _str_representer(dumper: yaml.SafeDumper, data: str) -> yaml.ScalarNode:
        if "\n" in data:
            return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
        return dumper.represent_scalar("tag:yaml.org,2002:str", data)

    _Dumper.add_representer(str, _str_representer)

    result = yaml.dump(step, Dumper=_Dumper, default_flow_style=False, sort_keys=False)
    return result.rstrip("\n")


def _render_workflow(
    dest: Path,
    hooks: dict[str, list[dict]],
    config: _WorkflowConfig | None = None,
) -> None:
    """Render the Jinja2 template with hook config and write to dest."""
    import jinja2

    template_env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(str(TEMPLATES_DIR)),
        variable_start_string="[[",
        variable_end_string="]]",
        block_start_string="[%",
        block_end_string="%]",
        comment_start_string="[#",
        comment_end_string="#]",
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    template_env.filters["step_yaml"] = _step_to_yaml
    if config is None:
        config = _WorkflowConfig()
    rendered = template_env.get_template("release.yml.j2").render(
        hooks=hooks,
        permissions=config.permissions,
        hook_jobs=config.hook_jobs,
    )
    dest.write_text(rendered)
